# Generated by Django 6.1 on 2026-08-29 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tariff',
            options={'ordering': ['price_monthly'], 'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
    ]
