# Generated by Django 6.1 on 2026-08-31 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0002_alter_tariff_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Файл изображения'),
        ),
    ]
