# Generated by Django 6.1 on 2026-08-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0003_image_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL изображения'),
        ),
    ]
