# Generated by Django 6.1 on 2026-09-03 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0005_tarifffeatureassignment_alter_tariff_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='orders/pdf/', verbose_name='PDF документа'),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
