# Generated by Django 6.1 on 2026-09-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0006_order_pdf_file_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('resolved', 'Обработана'), ('closed', 'Закрыта')], default='new', max_length=50, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='orders/pdf/', verbose_name='PDF документ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('processing', 'В обработке'), ('completed', 'Выполнен'), ('cancelled', 'Отменён'), ('refunded', 'Возвращён')], default='new', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
