# Generated by Django 6.1 on 2026-09-05 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0007_alter_contactrequest_status_alter_order_pdf_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='hosting.order', verbose_name='Заказ'),
        ),
    ]
